// Special-effect armor for the build optimizer's Armor tab — pieces that grant a
// UNIQUE passive buff (not plain defense), grouped by the buff they provide so a
// player can find e.g. damage- or bleed-boosting armor and locate it on the map.
//
// Effects/categories curated from eldenring.wiki.gg + Fextralife (base game + SotE);
// dlc / itemName / hasMap merged from our data/items.json (itemName drives the
// where-to-find map link). 56 pieces; 52 matched to map data.

export interface ArmorBuff {
  name: string
  slot: 'head' | 'chest' | 'arms' | 'legs'
  /** Set name when part of a multi-piece set (clubbed in the UI); else undefined. */
  set?: string
  /** Buff group (one of ARMOR_CATEGORIES). */
  category: string
  /** Concise mechanical effect. */
  effect: string
  magnitude?: string
  downside?: string
  dlc: boolean
  /** Matching items.json name (for the where-to-find link); undefined if unmatched. */
  itemName?: string
  /** Whether the matched item has map coordinates (locatable). */
  hasMap: boolean
}

/** Buff categories in display order (offensive first). */
export const ARMOR_CATEGORIES: string[] = ["Physical dmg","Bleed","Poison","Madness","Jump attacks","Sorcery potency","Incantation potency","Stat boost","HP/FP/Stamina","Utility"]

export const armorBuffs: ArmorBuff[] = [
  { name: 'Rakshasa Armor', slot: 'chest', category: 'Physical dmg', effect: 'Raises ALL damage dealt by +2% but also raises damage taken by +2%.', dlc: true, hasMap: true, set: 'Rakshasa Set', magnitude: '+2%', downside: '+2% damage taken', itemName: 'Rakshasa Armor' },
  { name: 'Rakshasa Gauntlets', slot: 'arms', category: 'Physical dmg', effect: 'Raises ALL damage dealt by +2% but also raises damage taken by +2%.', dlc: true, hasMap: true, set: 'Rakshasa Set', magnitude: '+2%', downside: '+2% damage taken', itemName: 'Rakshasa Gauntlets' },
  { name: 'Rakshasa Greaves', slot: 'legs', category: 'Physical dmg', effect: 'Raises ALL damage dealt by +2% but also raises damage taken by +2%.', dlc: true, hasMap: true, set: 'Rakshasa Set', magnitude: '+2%', downside: '+2% damage taken', itemName: 'Rakshasa Greaves' },
  { name: 'Rakshasa Helm', slot: 'head', category: 'Physical dmg', effect: 'Raises ALL damage dealt by +2% but also raises damage taken by +2% (defense negation values in the stat screen already reflect this penalty). Full set: +8% damage / +8% damage taken.', dlc: true, hasMap: true, set: 'Rakshasa Set', magnitude: '+2% damage per piece (+8% full set)', downside: '+2% damage taken per piece (defense already reduced in displayed stats)', itemName: 'Rakshasa Helm' },
  { name: 'White Mask', slot: 'head', category: 'Bleed', effect: 'Raises attack power by 10% for 20 seconds when blood loss is inflicted on any target nearby (including self). PvP reduced to 6% (Patch 1.09). Stacks with Lord of Blood\'s Exultation talisman. Also boosts spell damage.', dlc: false, hasMap: false, set: 'War Surgeon Set', magnitude: '+10% (PvE), +6% (PvP)', itemName: 'White Mask' },
  { name: 'Mushroom Crown', slot: 'head', category: 'Poison', effect: 'Raises attack power by 10% for 20 seconds when any target within ~7 meters is afflicted by Poison or Scarlet Rot (including wearer). Stacks with Kindred of Rot\'s Exultation talisman.', dlc: false, hasMap: true, set: 'Mushroom Set', magnitude: '+10%', itemName: 'Mushroom Crown' },
  { name: 'Black Dumpling', slot: 'head', category: 'Madness', effect: 'Raises ALL damage dealt by 10% for 60 seconds after the wearer suffers a full Madness proc. Buff persists even if the helm is removed after triggering. Howl of Shabriri is commonly used to intentionally trigger madness for this buff.', dlc: false, hasMap: false, magnitude: '+10% all damage', downside: 'Requires suffering a full Madness status effect to trigger', itemName: 'Black Dumpling' },
  { name: 'Gravebird\'s Blackquill Armor', slot: 'chest', category: 'Jump attacks', effect: 'Increases jump attack power by 10% in PvE (5% in PvP). Stacks with Claw Talisman and Raptor\'s Black Feathers.', dlc: true, hasMap: true, set: 'Gravebird Set', magnitude: '+10% (PvE), +5% (PvP)', itemName: 'Gravebird\'s Blackquill Armor' },
  { name: 'Raptor\'s Black Feathers', slot: 'chest', category: 'Jump attacks', effect: 'Strengthens jump attacks by +10% in PvE. Reduced to +5% in PvP (Patch 1.09). Stacks multiplicatively with Claw Talisman (+15%) for ~26.5% total jump attack boost.', dlc: false, hasMap: true, magnitude: '+10% (PvE), +5% (PvP)', itemName: 'Raptor\'s Black Feathers' },
  { name: 'Gravebird Helm', slot: 'head', category: 'Sorcery potency', effect: 'Increases the attack power of Rings of Spectral Light sorcery (and related spectral ring spells) by 15%.', dlc: true, hasMap: true, set: 'Gravebird Set', magnitude: '+15%', itemName: 'Gravebird Helm' },
  { name: 'Snow Witch Hat', slot: 'head', category: 'Sorcery potency', effect: 'Increases damage of cold sorceries by 10%. Specifically boosts: Adula\'s Moonblade, Glintstone Icecrag, Ranni\'s Dark Moon, Zamor Ice Storm. Does NOT boost Frostbite status itself.', dlc: false, hasMap: true, set: 'Snow Witch Set', magnitude: '+10%', itemName: 'Snow Witch Hat' },
  { name: 'Spellblade\'s Gloves', slot: 'arms', category: 'Sorcery potency', effect: 'Increases Magic damage from weapon skills (Ashes of War) by 2%.', dlc: false, hasMap: false, set: 'Spellblade Set', magnitude: '+2%', itemName: 'Spellblade\'s Gloves' },
  { name: 'Spellblade\'s Pointed Hat', slot: 'head', category: 'Sorcery potency', effect: 'Increases Magic damage from weapon skills (Ashes of War) by 2%. Does NOT boost sorcery spells directly — only magic-damage weapon skills.', dlc: false, hasMap: false, set: 'Spellblade Set', magnitude: '+2%', itemName: 'Spellblade\'s Pointed Hat' },
  { name: 'Spellblade\'s Traveling Attire', slot: 'chest', category: 'Sorcery potency', effect: 'Increases Magic damage from weapon skills (Ashes of War) by 2%.', dlc: false, hasMap: false, set: 'Spellblade Set', magnitude: '+2%', itemName: 'Spellblade\'s Traveling Attire' },
  { name: 'Spellblade\'s Trousers', slot: 'legs', category: 'Sorcery potency', effect: 'Increases Magic damage from weapon skills (Ashes of War) by 2%. Full set total: ~8% additive boost.', dlc: false, hasMap: false, set: 'Spellblade Set', magnitude: '+2%', itemName: 'Spellblade\'s Trousers' },
  { name: 'Crucible Axe Armor', slot: 'chest', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: true, set: 'Crucible Axe Set', magnitude: '+4%', itemName: 'Crucible Axe Armor' },
  { name: 'Crucible Axe Gauntlets', slot: 'arms', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: false, set: 'Crucible Axe Set', magnitude: '+4%' },
  { name: 'Crucible Axe Greaves', slot: 'legs', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: false, set: 'Crucible Axe Set', magnitude: '+4%' },
  { name: 'Crucible Axe Helm', slot: 'head', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%. Stacks multiplicatively with other Crucible set pieces (~17% total for 4 pieces).', dlc: false, hasMap: true, set: 'Crucible Axe Set', magnitude: '+4% per piece (~17% full set)', itemName: 'Crucible Axe Helm' },
  { name: 'Crucible Hammer-Helm', slot: 'head', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations (same buff as other Crucible set pieces, ~4%). Standalone helm; no matching armor set. Dropped by Devonia in Rauh Ancient Ruins (DLC).', dlc: true, hasMap: true, magnitude: '+4% (assumed, matches other Crucible pieces)', itemName: 'Crucible Hammer-Helm' },
  { name: 'Crucible Tree Armor', slot: 'chest', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: true, set: 'Crucible Tree Set', magnitude: '+4%', itemName: 'Crucible Tree Armor' },
  { name: 'Crucible Tree Gauntlets', slot: 'arms', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: false, set: 'Crucible Tree Set', magnitude: '+4%' },
  { name: 'Crucible Tree Greaves', slot: 'legs', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills by 4%.', dlc: false, hasMap: false, set: 'Crucible Tree Set', magnitude: '+4%' },
  { name: 'Crucible Tree Helm', slot: 'head', category: 'Incantation potency', effect: 'Strengthens Aspects of the Crucible incantations and related skills (Ash of War: Aspects of the Crucible: Wings, Devonia\'s Vortex) by 4%. Stacks multiplicatively with other Crucible set pieces (4 pieces = ~17% total).', dlc: false, hasMap: true, set: 'Crucible Tree Set', magnitude: '+4% per piece (~17% full set)', itemName: 'Crucible Tree Helm' },
  { name: 'Death Knight Armor', slot: 'chest', category: 'Incantation potency', effect: 'Enhances Dragon Cult incantations and specific lightning weapon skills by 2%.', dlc: true, hasMap: true, set: 'Death Knight Set', magnitude: '+2%', itemName: 'Death Knight Armor' },
  { name: 'Death Knight Gauntlets', slot: 'arms', category: 'Incantation potency', effect: 'Enhances Dragon Cult incantations and specific lightning weapon skills by 2%.', dlc: true, hasMap: true, set: 'Death Knight Set', magnitude: '+2%', itemName: 'Death Knight Gauntlets' },
  { name: 'Death Knight Greaves', slot: 'legs', category: 'Incantation potency', effect: 'Enhances Dragon Cult incantations and specific lightning weapon skills by 2%.', dlc: true, hasMap: true, set: 'Death Knight Set', magnitude: '+2%', itemName: 'Death Knight Greaves' },
  { name: 'Death Knight Helm', slot: 'head', category: 'Incantation potency', effect: 'Enhances Dragon Cult (ancient dragon cult) incantations and specific lightning weapon skills by 2%. Boosts: Lightning Spear variants, Honed Bolt, Ancient Dragons\' Lightning Spear/Strike, Lansseax\'s Glaive, Fortissax\'s Lightning Spear, Frozen Lightning Spear, Death Lightning, Electrocharge, plus skills Thunderbolt, Lightning Slash, Blinkbolt variants. Does NOT boost Electrify Armament, Dragonbolt, Bolt of Gransax, or Dragon King\'s Cragblade.', dlc: true, hasMap: true, set: 'Death Knight Set', magnitude: '+2% per piece (+8% full set)', itemName: 'Death Knight Helm' },
  { name: 'Albinauric Mask', slot: 'head', category: 'Stat boost', effect: 'Raises Arcane by +4, but reduces Flask of Crimson Tears HP recovery by 10%.', dlc: false, hasMap: true, magnitude: '+4 Arcane', downside: '-10% Crimson Flask healing', itemName: 'Albinauric Mask' },
  { name: 'Greathood', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence and Faith by +2 each, but reduces max HP by 9%.', dlc: false, hasMap: true, magnitude: '+2 Intelligence, +2 Faith', downside: '-9% HP', itemName: 'Greathood' },
  { name: 'Haligtree Knight Helm', slot: 'head', category: 'Stat boost', effect: 'Raises Faith by +2. No downsides.', dlc: false, hasMap: true, set: 'Haligtree Knight Set', magnitude: '+2 Faith', itemName: 'Haligtree Knight Helm' },
  { name: 'Haligtree Helm', slot: 'head', category: 'Stat boost', effect: 'Raises Faith by +1. No downsides. (Separate item from Haligtree Knight Helm.)', dlc: false, hasMap: false, set: 'Haligtree Set', magnitude: '+1 Faith', itemName: 'Haligtree Helm' },
  { name: 'Marais Mask', slot: 'head', category: 'Stat boost', effect: 'Raises Arcane by +1. No downsides.', dlc: false, hasMap: true, set: 'House Marais Set', magnitude: '+1 Arcane', itemName: 'Marais Mask' },
  { name: 'Imp Head (Cat)', slot: 'head', category: 'Stat boost', effect: 'Raises Intelligence by +2. No downsides.', dlc: false, hasMap: true, magnitude: '+2 Intelligence', itemName: 'Imp Head (Cat)' },
  { name: 'Imp Head (Corpse)', slot: 'head', category: 'Stat boost', effect: 'Raises Faith by +2. No downsides. Note: Becomes unobtainable after defeating Maliketh (Leyndell changes).', dlc: false, hasMap: true, magnitude: '+2 Faith', itemName: 'Imp Head (Corpse)' },
  { name: 'Imp Head (Elder)', slot: 'head', category: 'Stat boost', effect: 'Raises Arcane by +2. No downsides.', dlc: false, hasMap: true, magnitude: '+2 Arcane', itemName: 'Imp Head (Elder)' },
  { name: 'Imp Head (Fanged)', slot: 'head', category: 'Stat boost', effect: 'Raises Strength by +2. No downsides.', dlc: false, hasMap: true, magnitude: '+2 Strength', itemName: 'Imp Head (Fanged)' },
  { name: 'Imp Head (Lion)', slot: 'head', category: 'Stat boost', effect: 'Raises Vigor by +2. No downsides. Also has the highest poise among Imp Heads (+3 poise vs others).', dlc: true, hasMap: true, magnitude: '+2 Vigor', itemName: 'Imp Head (Lion)' },
  { name: 'Imp Head (Long-Tongued)', slot: 'head', category: 'Stat boost', effect: 'Raises Dexterity by +2. No downsides.', dlc: false, hasMap: true, magnitude: '+2 Dexterity', itemName: 'Imp Head (Long-Tongued)' },
  { name: 'Imp Head (Wolf)', slot: 'head', category: 'Stat boost', effect: 'Raises Endurance by +2. No downsides.', dlc: false, hasMap: true, magnitude: '+2 Endurance', itemName: 'Imp Head (Wolf)' },
  { name: 'Karolos Glintstone Crown', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence by +3, but reduces Stamina by 9%.', dlc: false, hasMap: true, magnitude: '+3 Intelligence', downside: '-9% Stamina', itemName: 'Karolos Glintstone Crown' },
  { name: 'Lazuli Glintstone Crown', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence and Dexterity by +3 each, but reduces max HP by 18%.', dlc: false, hasMap: true, magnitude: '+3 Intelligence, +3 Dexterity', downside: '-18% HP', itemName: 'Lazuli Glintstone Crown' },
  { name: 'Mask of Confidence', slot: 'head', category: 'Stat boost', effect: 'Raises Arcane by +3 (also increases item Discovery by 3 as a side effect of the Arcane boost). No downsides.', dlc: false, hasMap: true, magnitude: '+3 Arcane', itemName: 'Mask of Confidence' },
  { name: 'Okina Mask', slot: 'head', category: 'Stat boost', effect: 'Raises Dexterity by +3 but lowers Focus resistance by 44 (increases madness/sleep buildup taken).', dlc: false, hasMap: true, magnitude: '+3 Dexterity', downside: '-44 Focus (more susceptible to Madness/Sleep)', itemName: 'Okina Mask' },
  { name: 'Olivinus Glintstone Crown', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence by +3, but reduces max HP by 10%.', dlc: false, hasMap: true, magnitude: '+3 Intelligence', downside: '-10% HP', itemName: 'Olivinus Glintstone Crown' },
  { name: 'Twinsage Glintstone Crown', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence by +6, but reduces max HP by 9% and max Stamina by 9%.', dlc: false, hasMap: true, magnitude: '+6 Intelligence', downside: '-9% HP, -9% Stamina', itemName: 'Twinsage Glintstone Crown' },
  { name: 'Witch\'s Glintstone Crown', slot: 'head', category: 'Stat boost', effect: 'Increases Intelligence and Arcane by +3 each, but reduces max Stamina by 18%.', dlc: false, hasMap: true, magnitude: '+3 Intelligence, +3 Arcane', downside: '-18% Stamina', itemName: 'Witch\'s Glintstone Crown' },
  { name: 'Deathbed Dress', slot: 'chest', category: 'HP/FP/Stamina', effect: 'Heals nearby allies and Spirit Ashes for 2 HP per second within ~7 meter radius. The WEARER does not receive the healing. Standalone piece (not part of a set).', dlc: false, hasMap: true, magnitude: '2 HP/sec to nearby allies only', downside: 'Wearer receives no benefit; extremely low physical defense (0.6)', itemName: 'Deathbed Dress' },
  { name: 'Royal Remains Armor', slot: 'chest', category: 'HP/FP/Stamina', effect: 'Slowly regenerates 2 HP per second while wearer\'s HP is below 18% of maximum.', dlc: false, hasMap: false, set: 'Royal Remains Set', magnitude: '2 HP/sec', downside: 'Only activates below 18% HP', itemName: 'Royal Remains Armor' },
  { name: 'Royal Remains Gauntlets', slot: 'arms', category: 'HP/FP/Stamina', effect: 'Slowly regenerates 2 HP per second while wearer\'s HP is below 18% of maximum.', dlc: false, hasMap: false, set: 'Royal Remains Set', magnitude: '2 HP/sec', downside: 'Only activates below 18% HP', itemName: 'Royal Remains Gauntlets' },
  { name: 'Royal Remains Greaves', slot: 'legs', category: 'HP/FP/Stamina', effect: 'Slowly regenerates 2 HP per second while wearer\'s HP is below 18% of maximum.', dlc: false, hasMap: false, set: 'Royal Remains Set', magnitude: '2 HP/sec', downside: 'Only activates below 18% HP', itemName: 'Royal Remains Greaves' },
  { name: 'Royal Remains Helm', slot: 'head', category: 'HP/FP/Stamina', effect: 'Slowly regenerates 2 HP per second while wearer\'s HP is below 18% of maximum. Each piece of the set independently contributes 2 HP/sec; full set = 8 HP/sec.', dlc: false, hasMap: false, set: 'Royal Remains Set', magnitude: '2 HP/sec per piece (max 8 HP/sec full set)', downside: 'Only activates below 18% HP', itemName: 'Royal Remains Helm' },
  { name: 'Briar Armor', slot: 'chest', category: 'Utility', effect: 'Deals 25 fixed damage (before enemy negations) to enemies when performing a dodge roll into them. Highest damage of the Briar set pieces.', dlc: false, hasMap: false, set: 'Briar Set', magnitude: '25 damage per roll (flat)', itemName: 'Briar Armor' },
  { name: 'Briar Gauntlets', slot: 'arms', category: 'Utility', effect: 'Deals 18 fixed damage (before enemy negations) to enemies when performing a dodge roll into them.', dlc: false, hasMap: false, set: 'Briar Set', magnitude: '18 damage per roll (flat)', itemName: 'Briar Gauntlets' },
  { name: 'Briar Greaves', slot: 'legs', category: 'Utility', effect: 'Deals 18 fixed damage (before enemy negations) to enemies when performing a dodge roll into them. Full set total: 79 fixed damage per roll.', dlc: false, hasMap: false, set: 'Briar Set', magnitude: '18 damage per roll (flat)', itemName: 'Briar Greaves' },
  { name: 'Briar Helm', slot: 'head', category: 'Utility', effect: 'Deals 18 fixed damage (before enemy negations) to enemies when performing a dodge roll into them. Damage is flat/unscaled.', dlc: false, hasMap: false, set: 'Briar Set', magnitude: '18 damage per roll (flat)', itemName: 'Briar Helm' },
]
