// Weapon catalog for the build page's "Weapon list" tab — every guide weapon with
// its class, requirements, scaling grades, weight and damage types, grouped by
// weapon class. Stats from data/items.json (fan-API details); weapon class baked
// from the regulation data (weaponName -> weaponType). GENERATED. 388 weapons.

export interface CatalogWeapon {
  name: string
  weaponType: number
  classLabel: string
  dlc: boolean
  hasMap: boolean
  req?: { str?: number; dex?: number; int?: number; fai?: number; arc?: number }
  scaling?: { str?: string; dex?: string; int?: string; fai?: string; arc?: string }
  weight?: number
  damage?: string[]
}

/** Weapon classes present, in logical (enum) order. */
export const WEAPON_CLASSES: { type: number; label: string }[] = [{"type":1,"label":"Dagger"},{"type":3,"label":"Straight Sword"},{"type":5,"label":"Greatsword"},{"type":7,"label":"Colossal Sword"},{"type":9,"label":"Curved Sword"},{"type":11,"label":"Curved Greatsword"},{"type":13,"label":"Katana"},{"type":14,"label":"Twinblade"},{"type":15,"label":"Thrusting Sword"},{"type":16,"label":"Heavy Thrusting Sword"},{"type":17,"label":"Axe"},{"type":19,"label":"Greataxe"},{"type":21,"label":"Hammer"},{"type":23,"label":"Great Hammer"},{"type":24,"label":"Flail"},{"type":25,"label":"Spear"},{"type":28,"label":"Great Spear"},{"type":29,"label":"Halberd"},{"type":31,"label":"Reaper"},{"type":35,"label":"Fist"},{"type":37,"label":"Claw"},{"type":39,"label":"Whip"},{"type":41,"label":"Colossal Weapon"},{"type":50,"label":"Light Bow"},{"type":51,"label":"Bow"},{"type":53,"label":"Greatbow"},{"type":55,"label":"Crossbow"},{"type":56,"label":"Ballista"},{"type":57,"label":"Glintstone Staff"},{"type":61,"label":"Sacred Seal"},{"type":89,"label":"Perfume Bottle"},{"type":91,"label":"Throwing Blade"},{"type":92,"label":"Backhand Blade"},{"type":93,"label":"Light Greatsword"},{"type":94,"label":"Great Katana"},{"type":95,"label":"Beast Claw"}]

export const weaponCatalog: CatalogWeapon[] = [
  { name: 'Black Knife', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 8, dex: 12, fai: 18 }, scaling: { str: 'E', dex: 'D', fai: 'D' }, weight: 2, damage: ['Phys', 'Holy'] },
  { name: 'Blade of Calling', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 6, dex: 13, fai: 15 }, scaling: { str: 'D', dex: 'D', fai: 'C' }, weight: 1.5, damage: ['Phys', 'Holy'] },
  { name: 'Bloodstained Dagger', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 9, dex: 12 }, scaling: { str: 'C', dex: 'E' }, weight: 2, damage: ['Phys'] },
  { name: 'Celebrant\'s Sickle', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: false, req: { str: 6, dex: 11 }, scaling: { str: 'E', dex: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Cinquedea', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 10, dex: 10 }, scaling: { str: 'D', dex: 'E' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Crystal Knife', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 8, dex: 12, int: 9 }, scaling: { str: 'D', dex: 'D', int: 'D' }, weight: 2, damage: ['Phys', 'Magic'] },
  { name: 'Dagger', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 5, dex: 9 }, scaling: { str: 'D', dex: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Erdsteel Dagger', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 7, dex: 12, fai: 14 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 2, damage: ['Phys'] },
  { name: 'Fire Knight\'s Shortsword', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: false },
  { name: 'Glintstone Kris', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: false, req: { str: 5, dex: 12, int: 16 }, scaling: { str: 'E', dex: 'D', int: 'D' }, weight: 1.5, damage: ['Phys', 'Magic'] },
  { name: 'Great Knife', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: false, req: { str: 6, dex: 12 }, scaling: { str: 'E', dex: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Ivory Sickle', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 6, dex: 11, int: 13 }, scaling: { str: 'E', dex: 'D', int: 'D' }, weight: 2, damage: ['Phys', 'Magic'] },
  { name: 'Main-gauche', weaponType: 1, classLabel: 'Dagger', dlc: true, hasMap: true },
  { name: 'Miséricorde', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 7, dex: 12 }, scaling: { str: 'E', dex: 'D' }, weight: 2, damage: ['Phys'] },
  { name: 'Parrying Dagger', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: false, req: { str: 5, dex: 14 }, scaling: { str: 'E', dex: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Reduvia', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 5, dex: 13, arc: 13 }, scaling: { str: 'E', dex: 'D', arc: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Scorpion\'s Stinger', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 6, dex: 12 }, scaling: { str: 'D', dex: 'C' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Wakizashi', weaponType: 1, classLabel: 'Dagger', dlc: false, hasMap: true, req: { str: 9, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Broadsword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 10, dex: 10 }, scaling: { str: 'D', dex: 'E' }, weight: 4, damage: ['Phys'] },
  { name: 'Cane Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 8, dex: 11 }, scaling: { str: 'E', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Carian Knight\'s Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 10, dex: 10, int: 18 }, scaling: { str: 'D', dex: 'D', int: 'D' }, weight: 4, damage: ['Phys', 'Magic'] },
  { name: 'Coded Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { fai: 20 }, scaling: { fai: 'B' }, weight: 2.5, damage: ['Holy'] },
  { name: 'Crystal Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 13, dex: 10, int: 15 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 4.5, damage: ['Phys', 'Magic'] },
  { name: 'Golden Epitaph', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 12, dex: 10, fai: 14 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 3.5, damage: ['Phys', 'Holy'] },
  { name: 'Lazuli Glintstone Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 8 }, scaling: { str: 'D' }, weight: 3.5, damage: ['Phys', 'Magic'] },
  { name: 'Longsword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 10, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Lordsworn\'s Straight Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 10, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Miquellan Knight\'s Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 11, dex: 11, fai: 16 }, scaling: { str: 'D', dex: 'D', fai: 'E' }, weight: 3.5, damage: ['Phys', 'Holy'] },
  { name: 'Noble\'s Slender Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 8 }, scaling: { str: 'E' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Ornamental Straight Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 10, dex: 14 }, scaling: { str: 'E', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Regalia of Eochaid', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 12 }, scaling: { str: 'E' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Rotten Crystal Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 13, dex: 10, int: 15 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 4.5, damage: ['Phys', 'Magic'] },
  { name: 'Short Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 8, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Stone-Sheathed Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: true, hasMap: true },
  { name: 'Sword of Darkness', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false },
  { name: 'Sword of Light', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false },
  { name: 'Sword of Night and Flame', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 12, dex: 12, fai: 24 }, scaling: { str: 'E', dex: 'E', fai: 'D' }, weight: 4, damage: ['Phys', 'Magic', 'Fire'] },
  { name: 'Sword of St. Trina', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: true, req: { str: 10, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys', 'Magic'] },
  { name: 'Velvet Sword of St. Trina', weaponType: 3, classLabel: 'Straight Sword', dlc: true, hasMap: true },
  { name: 'Warhawk\'s Talon', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 10, dex: 16 }, scaling: { str: 'D', dex: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Weathered Straight Sword', weaponType: 3, classLabel: 'Straight Sword', dlc: false, hasMap: false, req: { str: 7, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Alabaster Lord\'s Sword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 12, int: 18 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 8, damage: ['Phys', 'Magic'] },
  { name: 'Banished Knight\'s Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 17 }, scaling: { str: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Bastard Sword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 16, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Blasphemous Blade', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 22, dex: 15, fai: 21 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 13.5, damage: ['Phys', 'Fire'] },
  { name: 'Claymore', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Dark Moon Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 11, int: 38 }, scaling: { str: 'D', dex: 'D', int: 'C' }, weight: 10, damage: ['Phys', 'Magic'] },
  { name: 'Death\'s Poker', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 15, dex: 17, int: 11 }, scaling: { str: 'D', dex: 'D', int: 'E' }, weight: 8.5, damage: ['Phys', 'Magic'] },
  { name: 'Flamberge', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 15, dex: 14 }, scaling: { str: 'D', dex: 'C' }, weight: 10, damage: ['Phys'] },
  { name: 'Forked Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 14, dex: 16 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Gargoyle\'s Blackblade', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 18, dex: 10, fai: 22 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 11.5, damage: ['Phys', 'Holy'] },
  { name: 'Gargoyle\'s Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 18, dex: 10 }, scaling: { str: 'C', dex: 'E' }, weight: 11.5, damage: ['Phys'] },
  { name: 'Golden Order Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 21, fai: 18 }, scaling: { str: 'E', dex: 'D', fai: 'C' }, weight: 10, damage: ['Phys', 'Holy'] },
  { name: 'Greatsword of Damnation', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false },
  { name: 'Greatsword of Solitude', weaponType: 5, classLabel: 'Greatsword', dlc: true, hasMap: true },
  { name: 'Helphen\'s Steeple', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 19, dex: 10, int: 22 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 11.5, damage: ['Phys', 'Magic'] },
  { name: 'Inseparable Sword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true },
  { name: 'Iron Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 18, dex: 10 }, scaling: { str: '?', dex: '?' }, weight: 12, damage: ['Phys'] },
  { name: 'Knight\'s Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 16, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Lizard Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false },
  { name: 'Lordsworn\'s Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Marais Executioner\'s Sword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 24, dex: 14, arc: 23 }, scaling: { str: 'C', dex: 'E', arc: 'D' }, weight: 11.5, damage: ['Phys', 'Magic'] },
  { name: 'Ordovis\'s Greatsword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 25, dex: 13, fai: 15 }, scaling: { str: 'C', dex: 'E', fai: 'D' }, weight: 12, damage: ['Phys', 'Holy'] },
  { name: 'Sacred Relic Sword', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: false, req: { str: 14, dex: 24, fai: 22 }, scaling: { str: 'E', dex: 'D', fai: 'D' }, weight: 11, damage: ['Phys', 'Holy'] },
  { name: 'Sword of Milos', weaponType: 5, classLabel: 'Greatsword', dlc: false, hasMap: true, req: { str: 15, dex: 19 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Ancient Meteoric Ore Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: true, hasMap: true },
  { name: 'Fire Knight\'s Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false },
  { name: 'Godslayer\'s Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 20, dex: 22, fai: 20 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 17.5, damage: ['Phys', 'Fire'] },
  { name: 'Grafted Blade Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 40, dex: 14 }, scaling: { str: 'C', dex: 'E' }, weight: 21, damage: ['Phys'] },
  { name: 'Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 31, dex: 12 }, scaling: { str: 'C', dex: 'E' }, weight: 23, damage: ['Phys'] },
  { name: 'Greatsword of Radahn (Light)', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false },
  { name: 'Greatsword of Radahn (Lord)', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false },
  { name: 'Maliketh\'s Black Blade', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false, req: { str: 34, dex: 12, fai: 20 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 22, damage: ['Phys', 'Holy'] },
  { name: 'Moonrithyll\'s Knight Sword', weaponType: 7, classLabel: 'Colossal Sword', dlc: true, hasMap: true },
  { name: 'Royal Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 26, dex: 18, int: 22 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 20, damage: ['Magic'] },
  { name: 'Ruins Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 50, int: 16 }, scaling: { str: 'B', int: 'D' }, weight: 23, damage: ['Phys', 'Magic'] },
  { name: 'Starscourge Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false, req: { str: 38, dex: 12, int: 15 }, scaling: { str: 'D', dex: 'D', int: 'E' }, weight: 20, damage: ['Phys', 'Magic'] },
  { name: 'Troll Knight\'s Sword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 20, dex: 14, int: 18 }, scaling: { str: 'D', dex: 'D', int: 'D' }, weight: 18, damage: ['Phys', 'Magic'] },
  { name: 'Troll\'s Golden Sword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: true, req: { str: 29, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 19, damage: ['Phys'] },
  { name: 'Watchdog\'s Greatsword', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false, req: { str: 30, dex: 10 }, scaling: { str: 'C', dex: 'E' }, weight: 22, damage: ['Phys'] },
  { name: 'Zweihander', weaponType: 7, classLabel: 'Colossal Sword', dlc: false, hasMap: false, req: { str: 19, dex: 11 }, scaling: { str: 'D', dex: 'D' }, weight: 15.5, damage: ['Phys'] },
  { name: 'Bandit\'s Curved Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false },
  { name: 'Beastman\'s Curved Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false, req: { str: 13, dex: 11 }, scaling: { str: 'C', dex: 'E' }, weight: 4, damage: ['Phys'] },
  { name: 'Dancing Blade of Ranah', weaponType: 9, classLabel: 'Curved Sword', dlc: true, hasMap: true },
  { name: 'Eclipse Shotel', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 10, dex: 25, fai: 30 }, scaling: { str: 'E', dex: 'D', fai: 'D' }, weight: 3, damage: ['Phys', 'Holy'] },
  { name: 'Falchion', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 9, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Falx', weaponType: 9, classLabel: 'Curved Sword', dlc: true, hasMap: true },
  { name: 'Flowing Curved Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 9, dex: 17 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Grossmesser', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false, req: { str: 14, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Horned Warrior\'s Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: true, hasMap: true },
  { name: 'Magma Blade', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false, req: { str: 9, dex: 15, fai: 16 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 4, damage: ['Phys', 'Fire'] },
  { name: 'Mantis Blade', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 10, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Nox Flowing Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 8, dex: 15 }, scaling: { str: 'E', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Scavenger\'s Curved Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 9, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Scimitar', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false, req: { str: 7, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Serpent-God\'s Curved Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 13, dex: 9 }, scaling: { str: 'D', dex: 'E' }, weight: 4, damage: ['Phys'] },
  { name: 'Shamshir', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 7, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Shotel', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: false, req: { str: 9, dex: 19 }, scaling: { str: 'E', dex: 'D' }, weight: 2, damage: ['Phys'] },
  { name: 'Spirit Sword', weaponType: 9, classLabel: 'Curved Sword', dlc: true, hasMap: true },
  { name: 'Wing of Astel', weaponType: 9, classLabel: 'Curved Sword', dlc: false, hasMap: true, req: { str: 7, dex: 17, int: 20 }, scaling: { str: 'E', dex: 'D', int: 'D' }, weight: 2.5, damage: ['Phys', 'Magic'] },
  { name: 'Beastman\'s Cleaver', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: false, req: { str: 25, dex: 14 }, scaling: { str: '?', dex: '?' }, weight: 16.5, damage: ['Phys'] },
  { name: 'Bloodhound\'s Fang', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: true, req: { str: 18, dex: 17 }, scaling: { str: 'D', dex: 'C' }, weight: 11.5, damage: ['Phys'] },
  { name: 'Dismounter', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: false, req: { str: 19, dex: 16 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Freyja\'s Greatsword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: true, hasMap: true },
  { name: 'Horned Warrior\'s Greatsword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: true, hasMap: true },
  { name: 'Magma Wyrm\'s Scalesword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: true, req: { str: 24, dex: 15, fai: 18 }, scaling: { str: 'C', dex: 'D', fai: 'D' }, weight: 15, damage: ['Phys', 'Fire'] },
  { name: 'Monk\'s Flameblade', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: false, req: { str: 18, dex: 18 }, scaling: { str: '?', dex: '?' }, weight: 9, damage: ['Phys'] },
  { name: 'Morgott\'s Cursed Sword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: false, req: { str: 14, dex: 35, arc: 17 }, scaling: { str: 'E', dex: 'C', arc: 'D' }, weight: 7.5, damage: ['Phys'] },
  { name: 'Omen Cleaver', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: true, req: { str: 19, dex: 16 }, scaling: { str: 'D', dex: 'D' }, weight: 11.5, damage: ['Phys'] },
  { name: 'Onyx Lord\'s Greatsword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: true, req: { str: 20, dex: 16, int: 16 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 11.5, damage: ['Phys', 'Magic'] },
  { name: 'Zamor Curved Sword', weaponType: 11, classLabel: 'Curved Greatsword', dlc: false, hasMap: true, req: { str: 16, dex: 18 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Dragonscale Blade', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 12, dex: 20 }, scaling: { str: 'D', dex: 'C' }, weight: 5.5, damage: ['Phys'] },
  { name: 'Hand of Malenia', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: false, req: { str: 16, dex: 48 }, scaling: { str: 'E', dex: 'B' }, weight: 7, damage: ['Phys'] },
  { name: 'Meteoric Ore Blade', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 15, dex: 14, int: 18 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 7.5, damage: ['Phys', 'Magic'] },
  { name: 'Moonveil', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 12, dex: 18, int: 23 }, scaling: { str: 'E', dex: 'D', int: 'C' }, weight: 6.5, damage: ['Phys', 'Magic'] },
  { name: 'Nagakiba', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 18, dex: 22 }, scaling: { str: 'D', dex: 'C' }, weight: 7, damage: ['Phys'] },
  { name: 'Rivers of Blood', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 12, dex: 18, arc: 20 }, scaling: { str: 'E', dex: 'D', arc: 'D' }, weight: 6.5, damage: ['Phys', 'Fire'] },
  { name: 'Serpentbone Blade', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 11, dex: 22 }, scaling: { str: 'E', dex: 'C' }, weight: 6 },
  { name: 'Star-Lined Sword', weaponType: 13, classLabel: 'Katana', dlc: true, hasMap: true },
  { name: 'Sword of Night', weaponType: 13, classLabel: 'Katana', dlc: true, hasMap: true },
  { name: 'Uchigatana', weaponType: 13, classLabel: 'Katana', dlc: false, hasMap: true, req: { str: 11, dex: 15 }, scaling: { str: 'D', dex: 'D' }, weight: 5.5, damage: ['Phys'] },
  { name: 'Black Steel Twinblade', weaponType: 14, classLabel: 'Twinblade', dlc: true, hasMap: true },
  { name: 'Eleonora\'s Poleblade', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 12, dex: 21, arc: 19 }, scaling: { str: 'E', dex: 'E', arc: 'D' }, weight: 6, damage: ['Phys', 'Fire'] },
  { name: 'Euporia', weaponType: 14, classLabel: 'Twinblade', dlc: true, hasMap: true },
  { name: 'Gargoyle\'s Black Blades', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 18, dex: 15, fai: 22 }, scaling: { str: 'C', dex: 'E', fai: 'D' }, weight: 8.5, damage: ['Phys', 'Holy'] },
  { name: 'Gargoyle\'s Twinblade', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 18, dex: 15 }, scaling: { str: 'C', dex: 'E' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Godskin Peeler', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 17, dex: 22 }, scaling: { str: 'E', dex: 'C' }, weight: 8, damage: ['Phys'] },
  { name: 'Twinblade', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 10, dex: 18 }, scaling: { str: 'D', dex: 'D' }, weight: 7, damage: ['Phys'] },
  { name: 'Twinned Knight Swords', weaponType: 14, classLabel: 'Twinblade', dlc: false, hasMap: true, req: { str: 16, dex: 18 }, scaling: { str: 'D', dex: 'E' }, weight: 8, damage: ['Phys'] },
  { name: 'Antspur Rapier', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: true, req: { str: 10, dex: 20 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Carian Sorcery Sword', weaponType: 15, classLabel: 'Thrusting Sword', dlc: true, hasMap: true },
  { name: 'Cleanrot Knight\'s Sword', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: false, req: { str: 13, dex: 11 }, scaling: { str: 'D', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Estoc', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: false, req: { str: 11, dex: 13 }, scaling: { str: 'E', dex: 'C' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Frozen Needle', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: true, req: { str: 11, dex: 18 }, scaling: { str: 'E', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Noble\'s Estoc', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: false, req: { str: 9, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Rapier', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: false, req: { str: 7, dex: 12 }, scaling: { str: 'E', dex: 'C' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Rogier\'s Rapier', weaponType: 15, classLabel: 'Thrusting Sword', dlc: false, hasMap: false, req: { str: 8, dex: 17 }, scaling: { str: 'E', dex: 'C' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Bloody Helice', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: false, hasMap: true, req: { str: 16, dex: 19, arc: 17 }, scaling: { str: 'E', dex: 'D', arc: 'D' }, weight: 8, damage: ['Phys'] },
  { name: 'Dragon King\'s Cragblade', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: false, hasMap: false, req: { str: 18, dex: 37 }, scaling: { str: 'E', dex: 'D' }, weight: 8, damage: ['Phys'] },
  { name: 'Godskin Stitcher', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: false, hasMap: true, req: { str: 14, dex: 17 }, scaling: { str: 'D', dex: 'D' }, weight: 7, damage: ['Phys'] },
  { name: 'Great Épée', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: false, hasMap: true, req: { str: 15, dex: 16 }, scaling: { str: 'D', dex: 'D' }, weight: 6.5, damage: ['Phys'] },
  { name: 'Queelign\'s Greatsword', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: true, hasMap: true },
  { name: 'Sword Lance', weaponType: 16, classLabel: 'Heavy Thrusting Sword', dlc: false, hasMap: false },
  { name: 'Battle Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 12, dex: 8 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Celebrant\'s Cleaver', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 12, dex: 8 }, scaling: { str: '?', dex: '?' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Death Knight\'s Twin Axes', weaponType: 17, classLabel: 'Axe', dlc: true, hasMap: true },
  { name: 'Forked Hatchet', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 9, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Forked-Tongue Hatchet', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false },
  { name: 'Hand Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 9, dex: 8 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Highland Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 12, dex: 9 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Icerind Hatchet', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 11, dex: 16 }, scaling: { str: 'E', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Iron Cleaver', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 15, dex: 7 }, scaling: { str: 'C', dex: 'E' }, weight: 6, damage: ['Phys'] },
  { name: 'Jawbone Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 14, dex: 8 }, scaling: { str: 'D', dex: 'E' }, weight: 5.5, damage: ['Phys'] },
  { name: 'Messmer Soldier\'s Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false },
  { name: 'Ripple Blade', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 11, dex: 11, arc: 20 }, scaling: { arc: 'A' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Rosus\' Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 18, dex: 10, int: 18 }, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Sacrificial Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 16, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 5.5, damage: ['Phys'] },
  { name: 'Smithscript Axe', weaponType: 17, classLabel: 'Axe', dlc: true, hasMap: true },
  { name: 'Stormhawk Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: true, req: { str: 19, dex: 15 }, scaling: { str: 'D', dex: 'D' }, weight: 5.5, damage: ['Phys'] },
  { name: 'Warped Axe', weaponType: 17, classLabel: 'Axe', dlc: false, hasMap: false, req: { str: 24, dex: 8 }, scaling: { str: 'C' }, weight: 7.5, damage: ['Phys'] },
  { name: 'Axe of Godrick', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: false, req: { str: 34, dex: 22 }, scaling: { str: 'D', dex: 'D' }, weight: 11, damage: ['Phys'] },
  { name: 'Bonny Butchering Knife', weaponType: 19, classLabel: 'Greataxe', dlc: true, hasMap: true },
  { name: 'Butchering Knife', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 16, dex: 20 }, scaling: { str: 'E', dex: 'C' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Crescent Moon Axe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: false, req: { str: 25, dex: 15 }, scaling: { str: 'D', dex: 'D' }, weight: 12.5, damage: ['Phys'] },
  { name: 'Death Knight\'s Longhaft Axe', weaponType: 19, classLabel: 'Greataxe', dlc: true, hasMap: true },
  { name: 'Executioner\'s Greataxe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: false, req: { str: 34, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 15, damage: ['Phys'] },
  { name: 'Gargoyle\'s Black Axe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 24, dex: 8, fai: 22 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 8.5, damage: ['Phys', 'Holy'] },
  { name: 'Gargoyle\'s Great Axe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 24, dex: 8 }, scaling: { str: 'C', dex: 'E' }, damage: ['Phys'] },
  { name: 'Great Omenkiller Cleaver', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 23, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 11, damage: ['Phys'] },
  { name: 'Greataxe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 30, dex: 8 }, scaling: { str: 'D', dex: 'D' }, weight: 13, damage: ['Phys'] },
  { name: 'Longhaft Axe', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 24, dex: 8 }, scaling: { str: '?', dex: '?' }, weight: 12.5, damage: ['Phys'] },
  { name: 'Putrescence Cleaver', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: false },
  { name: 'Rusted Anchor', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: true, req: { str: 26, dex: 9 }, scaling: { str: 'C', dex: 'E' }, weight: 12.5, damage: ['Phys'] },
  { name: 'Winged Greathorn', weaponType: 19, classLabel: 'Greataxe', dlc: false, hasMap: false, req: { str: 30, dex: 20 }, scaling: { str: 'D', dex: 'D' }, weight: 11, damage: ['Phys'] },
  { name: 'Club', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 10 }, scaling: { str: 'C' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Curved Club', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 11, dex: 7 }, scaling: { str: '?', dex: '?' }, weight: 5, damage: ['Phys'] },
  { name: 'Envoy\'s Horn', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 10 }, scaling: { str: 'D' }, weight: 4, damage: ['Phys', 'Holy'] },
  { name: 'Flowerstone Gavel', weaponType: 21, classLabel: 'Hammer', dlc: true, hasMap: true },
  { name: 'Hammer', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 14, dex: 7 }, scaling: { str: 'D', dex: 'D' }, weight: 6.5, damage: ['Phys'] },
  { name: 'Mace', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 12, dex: 7 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Marika\'s Hammer', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 20 }, scaling: { str: 'D' }, weight: 6, damage: ['Phys', 'Holy'] },
  { name: 'Monk\'s Flamemace', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 13, dex: 13 }, scaling: { str: 'E', dex: 'D' }, weight: 6, damage: ['Phys'] },
  { name: 'Morning Star', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 12, dex: 8 }, scaling: { str: 'D', dex: 'D' }, weight: 5, damage: ['Phys'] },
  { name: 'Nox Flowing Hammer', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 17, dex: 7 }, scaling: { str: 'C', dex: 'E' }, weight: 6.5, damage: ['Phys'] },
  { name: 'Ringed Finger', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 17, dex: 7 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Scepter of the All-Knowing', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 12, dex: 18, int: 21 }, scaling: { str: 'E', dex: 'D', int: 'D' }, weight: 4.5, damage: ['Phys', 'Magic'] },
  { name: 'Spiked Club', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 12, dex: 7 }, scaling: { str: 'D', dex: 'D' }, weight: 5, damage: ['Phys'] },
  { name: 'Stone Club', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: false, req: { str: 16, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 7, damage: ['Phys'] },
  { name: 'Varré\'s Bouquet', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 8, dex: 16, arc: 24 }, scaling: { str: 'E', dex: 'D', arc: 'C' }, weight: 2, damage: ['Phys'] },
  { name: 'Warpick', weaponType: 21, classLabel: 'Hammer', dlc: false, hasMap: true, req: { str: 11, dex: 9 }, scaling: { str: 'D', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Battle Hammer', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 26, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 10, damage: ['Phys'] },
  { name: 'Beastclaw Greathammer', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 20, dex: 10, fai: 18 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 9, damage: ['Phys', 'Holy'] },
  { name: 'Black Steel Greathammer', weaponType: 23, classLabel: 'Great Hammer', dlc: true, hasMap: true },
  { name: 'Brick Hammer', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 31 }, scaling: { str: 'B' }, weight: 12.5, damage: ['Phys'] },
  { name: 'Celebrant\'s Skull', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 18, dex: 12 }, scaling: { str: '?', dex: '?' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Cranial Vessel Candlestand', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 26, dex: 8, fai: 22 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 12.5, damage: ['Phys', 'Fire'] },
  { name: 'Curved Great Club', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: false, req: { str: 24, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Devourer\'s Scepter', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 24, dex: 20, fai: 25 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 11.5, damage: ['Phys', 'Fire'] },
  { name: 'Envoy\'s Long Horn', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: false, req: { str: 23, dex: 11, fai: 18 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 9.5, damage: ['Phys', 'Holy'] },
  { name: 'Great Mace', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 28 }, scaling: { str: 'C' }, weight: 11.5, damage: ['Phys'] },
  { name: 'Great Stars', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 22 }, scaling: { str: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Greathorn Hammer', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 22, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Large Club', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 22 }, scaling: { str: 'C' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Pickaxe', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: false, req: { str: 22, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Rotten Battle Hammer', weaponType: 23, classLabel: 'Great Hammer', dlc: false, hasMap: true, req: { str: 26, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 10, damage: ['Phys'] },
  { name: 'Smithscript Greathammer', weaponType: 23, classLabel: 'Great Hammer', dlc: true, hasMap: true },
  { name: 'Bastard\'s Stars', weaponType: 24, classLabel: 'Flail', dlc: false, hasMap: false, req: { str: 8, dex: 22, int: 22 }, scaling: { str: 'E', dex: 'D', int: 'C' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Chainlink Flail', weaponType: 24, classLabel: 'Flail', dlc: false, hasMap: false, req: { str: 18, dex: 12 }, scaling: { str: 'C', dex: 'E' }, weight: 8, damage: ['Phys'] },
  { name: 'Family Heads', weaponType: 24, classLabel: 'Flail', dlc: false, hasMap: true, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Flail', weaponType: 24, classLabel: 'Flail', dlc: false, hasMap: true, req: { str: 10, dex: 18 }, scaling: { str: 'D', dex: 'D' }, weight: 5, damage: ['Phys'] },
  { name: 'Nightrider Flail', weaponType: 24, classLabel: 'Flail', dlc: false, hasMap: true, req: { str: 10, dex: 24 }, scaling: { str: 'E', dex: 'C' }, weight: 6, damage: ['Phys'] },
  { name: 'Serpent Flail', weaponType: 24, classLabel: 'Flail', dlc: true, hasMap: true },
  { name: 'Bloodfiend\'s Fork', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false },
  { name: 'Bolt of Gransax', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 20, dex: 40 }, scaling: { str: 'D', dex: 'D' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Celebrant\'s Rib-Rake', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 8, dex: 14 }, scaling: { str: '?', dex: '?' }, weight: 5, damage: ['Phys'] },
  { name: 'Clayman\'s Harpoon', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, scaling: { str: 'D', dex: 'E', int: 'D' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Cleanrot Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 16 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 5.5, damage: ['Phys', 'Holy'] },
  { name: 'Cross-Naginata', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 16, dex: 20 }, scaling: { str: 'D', dex: 'C' }, weight: 8, damage: ['Phys'] },
  { name: 'Crystal Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 10, dex: 16, int: 16 }, scaling: { str: '?', dex: '?', int: '?' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Death Ritual Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 11, dex: 20, int: 18 }, scaling: { str: 'E', dex: 'D', int: 'D' }, weight: 6.5, damage: ['Phys', 'Magic'] },
  { name: 'Inquisitor\'s Girandole', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 18, dex: 15, fai: 16 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 7.5, damage: ['Phys', 'Fire'] },
  { name: 'Iron Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 13, dex: 11 }, scaling: { str: 'D', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Partisan', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 15, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 6.5, damage: ['Phys'] },
  { name: 'Pike', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 20, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 7.5, damage: ['Phys'] },
  { name: 'Rotten Crystal Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 10, dex: 16, int: 16 }, scaling: { str: '?', dex: '?', int: '?' }, weight: 5.5, damage: ['Phys', 'Magic'] },
  { name: 'Short Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 10, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Smithscript Spear', weaponType: 25, classLabel: 'Spear', dlc: true, hasMap: true },
  { name: 'Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 12, dex: 15 }, scaling: { str: 'E', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Spiked Spear', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: true, req: { str: 14 }, scaling: { str: 'D' }, weight: 6, damage: ['Phys'] },
  { name: 'Swift Spear', weaponType: 25, classLabel: 'Spear', dlc: true, hasMap: true },
  { name: 'Torchpole', weaponType: 25, classLabel: 'Spear', dlc: false, hasMap: false, req: { str: 14, dex: 15 }, scaling: { str: 'D', dex: 'D', fai: 'E' }, weight: 6, damage: ['Phys', 'Fire'] },
  { name: 'Barbed Staff-Spear', weaponType: 28, classLabel: 'Great Spear', dlc: true, hasMap: true },
  { name: 'Bloodfiend\'s Sacred Spear', weaponType: 28, classLabel: 'Great Spear', dlc: true, hasMap: true },
  { name: 'Lance', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: true, req: { str: 20, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 9, damage: ['Phys'] },
  { name: 'Messmer Soldier\'s Spear', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: false },
  { name: 'Mohgwyn\'s Sacred Spear', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: false, req: { str: 24, arc: 27, dex: 14 }, scaling: { str: 'D', arc: 'D', dex: 'E' }, weight: 10, damage: ['Phys', 'Fire'] },
  { name: 'Serpent-Hunter', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: true, scaling: { str: 'B', dex: 'E' }, weight: 12, damage: ['Phys'] },
  { name: 'Siluria\'s Tree', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: true, req: { str: 27, dex: 13 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 10, damage: ['Phys', 'Holy'] },
  { name: 'Spear of the Impaler', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: false },
  { name: 'Treespear', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: true, req: { str: 15, dex: 22 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 9.5, damage: ['Phys', 'Holy'] },
  { name: 'Vyke\'s War Spear', weaponType: 28, classLabel: 'Great Spear', dlc: false, hasMap: true, req: { str: 16, dex: 20, fai: 18 }, scaling: { str: 'E', dex: 'C', fai: 'D' }, weight: 8, damage: ['Phys', 'Fire'] },
  { name: 'Banished Knight\'s Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 14, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 8, damage: ['Phys'] },
  { name: 'Commander\'s Standard', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 24, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 11.5, damage: ['Phys'] },
  { name: 'Dragon Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 22, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 10.5, damage: ['Phys'] },
  { name: 'Gargoyle\'s Black Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 26, dex: 10, fai: 22 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 12, damage: ['Phys', 'Holy'] },
  { name: 'Gargoyle\'s Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 26, dex: 10 }, scaling: { str: 'C', dex: 'E' }, weight: 12, damage: ['Phys'] },
  { name: 'Glaive', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 18, dex: 15 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Golden Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 30, dex: 14, fai: 12 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 13.5, damage: ['Phys', 'Holy'] },
  { name: 'Guardian\'s Swordspear', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 17, dex: 16 }, scaling: { str: 'E', dex: 'C' }, weight: 9, damage: ['Phys'] },
  { name: 'Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 14, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 8, damage: ['Phys'] },
  { name: 'Loretta\'s War Sickle', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 20, dex: 15, int: 20 }, scaling: { str: 'D', dex: 'D', int: 'D' }, weight: 10, damage: ['Phys', 'Magic'] },
  { name: 'Lucerne', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 15, dex: 12 }, scaling: { str: 'D', dex: 'C' }, weight: 7, damage: ['Phys'] },
  { name: 'Nightrider Glaive', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: true, req: { str: 26, dex: 10 }, scaling: { str: 'C', dex: 'E' }, weight: 12, damage: ['Phys'] },
  { name: 'Pest\'s Glaive', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 13, dex: 13 }, scaling: { str: 'D', dex: 'D' }, weight: 7, damage: ['Phys'] },
  { name: 'Poleblade of the Bud', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false },
  { name: 'Ripple Crescent Halberd', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 12 }, scaling: { arc: 'B' }, weight: 8.5, damage: ['Phys'] },
  { name: 'Spirit Glaive', weaponType: 29, classLabel: 'Halberd', dlc: true, hasMap: true },
  { name: 'Vulgar Militia Saw', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 15 }, scaling: { str: 'D' }, weight: 8, damage: ['Phys'] },
  { name: 'Vulgar Militia Shotel', weaponType: 29, classLabel: 'Halberd', dlc: false, hasMap: false, req: { str: 14, dex: 16 }, scaling: { str: 'E', dex: 'C' }, weight: 8, damage: ['Phys'] },
  { name: 'Grave Scythe', weaponType: 31, classLabel: 'Reaper', dlc: false, hasMap: false, req: { str: 17 }, scaling: { str: 'D' }, weight: 9.5, damage: ['Phys'] },
  { name: 'Halo Scythe', weaponType: 31, classLabel: 'Reaper', dlc: false, hasMap: false, req: { str: 13, dex: 16, fai: 15 }, scaling: { str: 'D', dex: 'D', fai: 'E' }, weight: 8.5, damage: ['Phys', 'Holy'] },
  { name: 'Obsidian Lamina', weaponType: 31, classLabel: 'Reaper', dlc: true, hasMap: true },
  { name: 'Scythe', weaponType: 31, classLabel: 'Reaper', dlc: false, hasMap: true, req: { str: 14, dex: 14 }, scaling: { str: 'E', dex: 'C' }, weight: 7.5, damage: ['Phys'] },
  { name: 'Winged Scythe', weaponType: 31, classLabel: 'Reaper', dlc: false, hasMap: true, req: { str: 16, dex: 16, fai: 24 }, scaling: { str: 'E', dex: 'D', fai: 'D' }, weight: 7.5, damage: ['Phys', 'Holy'] },
  { name: 'Caestus', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false, req: { str: 8, dex: 8 }, scaling: { str: 'D', dex: 'D' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Cipher Pata', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false, req: { fai: 30 }, scaling: { fai: 'C' }, damage: ['Holy'] },
  { name: 'Clinging Bone', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false, req: { str: 8, dex: 22, arc: 16 }, scaling: { str: 'E', dex: 'C', arc: 'D' }, weight: 2.5, damage: ['Phys', 'Magic'] },
  { name: 'Golem Fist', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false },
  { name: 'Grafted Dragon', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false, req: { str: 20, dex: 14, fai: 16 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 2.5, damage: ['Phys', 'Fire'] },
  { name: 'Iron Ball', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: true, req: { str: 11, dex: 8 }, scaling: { str: '?', dex: '?' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Katar', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: true, req: { str: 8, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Pata', weaponType: 35, classLabel: 'Fist', dlc: true, hasMap: true },
  { name: 'Poisoned Hand', weaponType: 35, classLabel: 'Fist', dlc: true, hasMap: true },
  { name: 'Spiked Caestus', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: false, req: { str: 8, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 2, damage: ['Phys'] },
  { name: 'Star Fist', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: true, req: { str: 12, dex: 8 }, scaling: { str: 'D', dex: 'E' }, weight: 3, damage: ['Phys'] },
  { name: 'Thiollier\'s Hidden Needle', weaponType: 35, classLabel: 'Fist', dlc: true, hasMap: true },
  { name: 'Veteran\'s Prosthesis', weaponType: 35, classLabel: 'Fist', dlc: false, hasMap: true, req: { str: 15, dex: 12 }, scaling: { str: 'D', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Bloodhound Claws', weaponType: 37, classLabel: 'Claw', dlc: false, hasMap: true, req: { str: 10, dex: 15 }, scaling: { str: 'D', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Claws of Night', weaponType: 37, classLabel: 'Claw', dlc: true, hasMap: true },
  { name: 'Hookclaws', weaponType: 37, classLabel: 'Claw', dlc: false, hasMap: true, req: { str: 8, dex: 14 }, scaling: { str: 'E', dex: 'C' }, weight: 2, damage: ['Phys'] },
  { name: 'Raptor Talons', weaponType: 37, classLabel: 'Claw', dlc: false, hasMap: true, req: { str: 6, dex: 14 }, scaling: { str: 'E', dex: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Venomous Fang', weaponType: 37, classLabel: 'Claw', dlc: false, hasMap: true, req: { str: 9, dex: 9 }, scaling: { str: 'D', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Giant\'s Red Braid', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: false, req: { str: 18, dex: 12, fai: 21 }, scaling: { str: 'D', dex: 'D', fai: 'D' }, weight: 2.5, damage: ['Phys', 'Fire'] },
  { name: 'Hoslow\'s Petal Whip', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: true, req: { str: 10, dex: 20 }, scaling: { str: 'D', dex: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Magma Whip Candlestick', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: true, req: { str: 8, dex: 16, fai: 18 }, scaling: { str: 'E', dex: 'D', fai: 'D' }, weight: 2.5, damage: ['Phys', 'Fire'] },
  { name: 'Thorned Whip', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: false, req: { str: 8, dex: 16 }, scaling: { str: 'E', dex: 'C' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Tooth Whip', weaponType: 39, classLabel: 'Whip', dlc: true, hasMap: true },
  { name: 'Urumi', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: true, req: { str: 10, dex: 19 }, scaling: { str: 'E', dex: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Whip', weaponType: 39, classLabel: 'Whip', dlc: false, hasMap: true, req: { str: 8, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 2, damage: ['Phys'] },
  { name: 'Anvil Hammer', weaponType: 41, classLabel: 'Colossal Weapon', dlc: true, hasMap: true },
  { name: 'Axe of Godfrey', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: false, req: { str: 42, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 18, damage: ['Phys'] },
  { name: 'Bloodfiend\'s Arm', weaponType: 41, classLabel: 'Colossal Weapon', dlc: true, hasMap: true },
  { name: 'Devonia\'s Hammer', weaponType: 41, classLabel: 'Colossal Weapon', dlc: true, hasMap: true },
  { name: 'Dragon Greatclaw', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 30, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 16, damage: ['Phys'] },
  { name: 'Duelist Greataxe', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: false, req: { str: 30, dex: 10 }, scaling: { str: 'E', dex: 'D' }, weight: 20, damage: ['Phys'] },
  { name: 'Envoy\'s Greathorn', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: false, req: { str: 28 }, scaling: { str: 'D' }, weight: 19.5, damage: ['Phys', 'Holy'] },
  { name: 'Fallingstar Beast Jaw', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 34, dex: 12, int: 20 }, scaling: { str: 'D', dex: 'D', int: 'E' }, weight: 21.5, damage: ['Phys', 'Magic'] },
  { name: 'Gazing Finger', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: false },
  { name: 'Ghiza\'s Wheel', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 28, dex: 18 }, scaling: { str: 'D', dex: 'D' }, weight: 19, damage: ['Phys'] },
  { name: 'Giant-Crusher', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 60 }, scaling: { str: 'C' }, weight: 26.5, damage: ['Phys'] },
  { name: 'Golem\'s Halberd', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 36, dex: 14 }, scaling: { str: 'D', dex: 'D' }, weight: 21.5, damage: ['Phys'] },
  { name: 'Great Club', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 35 }, scaling: { str: 'C' }, weight: 17, damage: ['Phys'] },
  { name: 'Prelate\'s Inferno Crozier', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 45, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 23.5, damage: ['Phys'] },
  { name: 'Rotten Greataxe', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 30, dex: 10 }, scaling: { str: 'E', dex: 'D' }, weight: 20, damage: ['Phys'] },
  { name: 'Rotten Staff', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 34, dex: 8 }, scaling: { str: 'C', dex: 'E' }, weight: 18, damage: ['Phys'] },
  { name: 'Shadow Sunflower Blossom', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: false },
  { name: 'Staff of the Avatar', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 34 }, scaling: { str: 'C' }, weight: 20, damage: ['Phys', 'Holy'] },
  { name: 'Troll\'s Hammer', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 28, dex: 8, fai: 10 }, scaling: { str: 'D', dex: 'E', fai: 'D' }, weight: 16, damage: ['Phys', 'Fire'] },
  { name: 'Watchdog\'s Staff', weaponType: 41, classLabel: 'Colossal Weapon', dlc: false, hasMap: true, req: { str: 34, dex: 10 }, scaling: { str: 'D', dex: 'D' }, weight: 19, damage: ['Phys'] },
  { name: 'Bone Bow', weaponType: 50, classLabel: 'Light Bow', dlc: true, hasMap: true },
  { name: 'Composite Bow', weaponType: 50, classLabel: 'Light Bow', dlc: false, hasMap: false, req: { str: 15, dex: 15 }, scaling: { str: 'E', dex: 'D' }, weight: 3, damage: ['Phys'] },
  { name: 'Harp Bow', weaponType: 50, classLabel: 'Light Bow', dlc: false, hasMap: true, req: { str: 9, dex: 9 }, scaling: { str: 'E', dex: 'E' }, weight: 2, damage: ['Phys'] },
  { name: 'Misbegotten Shortbow', weaponType: 50, classLabel: 'Light Bow', dlc: false, hasMap: true, req: { str: 16, dex: 8 }, scaling: { str: 'D', dex: 'E' }, weight: 3, damage: ['Phys'] },
  { name: 'Red Branch Shortbow', weaponType: 50, classLabel: 'Light Bow', dlc: false, hasMap: true, req: { str: 8, dex: 16 }, scaling: { str: 'E', dex: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Shortbow', weaponType: 50, classLabel: 'Light Bow', dlc: false, hasMap: false, req: { str: 8, dex: 10 }, scaling: { str: 'E', dex: 'E' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Albinauric Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: false, req: { str: 7, dex: 18 }, scaling: { str: 'E', dex: 'D' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Ansbach\'s Longbow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: false },
  { name: 'Black Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: true, req: { str: 9, dex: 20 }, scaling: { str: 'E', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Erdtree Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: true, req: { str: 8, dex: 12, fai: 14 }, scaling: { str: 'E', dex: 'E', fai: 'D' }, weight: 4, damage: ['Phys', 'Holy'] },
  { name: 'Horn Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: true, req: { str: 10, dex: 14, int: 12 }, scaling: { str: 'E', dex: 'D' }, weight: 4.5, damage: ['Phys', 'Magic'] },
  { name: 'Longbow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: false, req: { str: 9, dex: 14 }, scaling: { str: 'E', dex: 'D' }, weight: 4, damage: ['Phys'] },
  { name: 'Pulley Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: true, req: { str: 11, dex: 11 }, scaling: { str: 'D', dex: 'D' }, weight: 5, damage: ['Phys'] },
  { name: 'Serpent Bow', weaponType: 51, classLabel: 'Bow', dlc: false, hasMap: true, req: { str: 8, dex: 15, arc: 11 }, scaling: { str: 'E', dex: 'D', arc: 'D' }, weight: 3.5, damage: ['Phys'] },
  { name: 'Erdtree Greatbow', weaponType: 53, classLabel: 'Greatbow', dlc: false, hasMap: true, req: { str: 20, dex: 14, fai: 14 }, scaling: { str: 'E', dex: 'E', fai: 'D' }, weight: 11, damage: ['Phys', 'Holy'] },
  { name: 'Golem Greatbow', weaponType: 53, classLabel: 'Greatbow', dlc: false, hasMap: true, req: { str: 24, dex: 18 }, scaling: { str: 'D', dex: 'E' }, weight: 14.5, damage: ['Phys'] },
  { name: 'Greatbow', weaponType: 53, classLabel: 'Greatbow', dlc: false, hasMap: true, req: { str: 20, dex: 20 }, scaling: { str: 'D', dex: 'D' }, weight: 10, damage: ['Phys'] },
  { name: 'Igon\'s Greatbow', weaponType: 53, classLabel: 'Greatbow', dlc: true, hasMap: true },
  { name: 'Lion Greatbow', weaponType: 53, classLabel: 'Greatbow', dlc: false, hasMap: false, req: { str: 22, dex: 18 }, scaling: { str: 'D', dex: 'D' }, weight: 9.5, damage: ['Phys'] },
  { name: 'Arbalest', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: true, req: { str: 18, dex: 12 }, weight: 6, damage: ['Phys'] },
  { name: 'Crepus\'s Black-Key Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: false, req: { str: 14, dex: 16 }, weight: 5, damage: ['Phys'] },
  { name: 'Full Moon Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: true, req: { str: 10, dex: 10, int: 14 }, weight: 4, damage: ['Phys', 'Magic'] },
  { name: 'Heavy Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: false, req: { str: 14, dex: 10 }, weight: 5.5, damage: ['Phys'] },
  { name: 'Light Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: false, req: { str: 12, dex: 8 }, weight: 4, damage: ['Phys'] },
  { name: 'Pulley Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: true, req: { str: 16, dex: 16 }, weight: 4, damage: ['Phys'] },
  { name: 'Repeating Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: true, hasMap: true },
  { name: 'Soldier\'s Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: false, hasMap: false, req: { str: 10, dex: 8 }, weight: 3.5, damage: ['Phys'] },
  { name: 'Spread Crossbow', weaponType: 55, classLabel: 'Crossbow', dlc: true, hasMap: true },
  { name: 'Hand Ballista', weaponType: 56, classLabel: 'Ballista', dlc: false, hasMap: true, req: { str: 30, dex: 14 }, weight: 10, damage: ['Phys'] },
  { name: 'Jar Cannon', weaponType: 56, classLabel: 'Ballista', dlc: false, hasMap: true, req: { str: 34, dex: 12 }, weight: 15, damage: ['Phys'] },
  { name: 'Rabbath\'s Cannon', weaponType: 56, classLabel: 'Ballista', dlc: true, hasMap: true },
  { name: 'Academy Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 28 }, scaling: { str: 'E', int: 'B' }, weight: 3, damage: ['Phys'] },
  { name: 'Albinauric Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 10, arc: 12 }, scaling: { str: 'E', int: 'D', arc: 'C' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Astrologer\'s Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 7, int: 16 }, scaling: { str: 'E', int: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Azur\'s Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 10, int: 52 }, scaling: { str: 'D', int: 'B' }, weight: 4, damage: ['Phys'] },
  { name: 'Carian Glintblade Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 22, dex: 12 }, scaling: { str: 'E', int: 'C', dex: 'E' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Carian Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 24, dex: 8 }, scaling: { str: 'E', int: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Carian Regal Scepter', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 8, dex: 10, int: 60 }, scaling: { str: 'E', dex: 'E', int: 'B' }, weight: 3, damage: ['Phys'] },
  { name: 'Crystal Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 8, int: 48 }, scaling: { str: 'D', int: 'B' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Demi-Human Queen\'s Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 10 }, scaling: { str: 'D', int: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Digger\'s Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 8, int: 12 }, scaling: { str: 'D', int: 'C' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Gelmir Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 6, int: 14, fai: 14 }, scaling: { str: 'E', int: 'D', fai: 'D' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 6, int: 10 }, scaling: { str: 'E', int: 'C' }, weight: 3, damage: ['Phys'] },
  { name: 'Lusat\'s Glintstone Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 10, int: 52 }, scaling: { str: 'D', int: 'B' }, weight: 4, damage: ['Phys'] },
  { name: 'Maternal Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: true, hasMap: true },
  { name: 'Meteorite Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, int: 18 }, scaling: { str: 'D', int: 'S' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Prince of Death\'s Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true },
  { name: 'Rotten Crystal Staff', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 8, int: 48 }, scaling: { str: 'D', int: 'B' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Staff of Loss', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: true, req: { str: 6, dex: 12, int: 14 }, scaling: { str: 'E', dex: 'E', int: 'C' }, weight: 2.5, damage: ['Phys'] },
  { name: 'Staff of the Great Beyond', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false },
  { name: 'Staff of the Guilty', weaponType: 57, classLabel: 'Glintstone Staff', dlc: false, hasMap: false, req: { str: 8, fai: 12 }, scaling: { str: 'D', fai: 'C' }, weight: 4.5, damage: ['Phys'] },
  { name: 'Clawmark Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { str: 4, fai: 10 }, scaling: { str: 'D', fai: 'D' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Dragon Communion Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { fai: 10, arc: 10 }, scaling: { fai: 'D', arc: 'C' }, damage: ['Phys'] },
  { name: 'Dryleaf Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: true, hasMap: true },
  { name: 'Erdtree Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { fai: 40 }, scaling: { fai: 'C' }, damage: ['Phys', 'Holy'] },
  { name: 'Finger Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: false, req: { str: 4, fai: 10 }, scaling: { str: 'E', fai: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Fire Knight\'s Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: true, hasMap: true },
  { name: 'Frenzied Flame Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { fai: 10, arc: 10 }, scaling: { str: 'E', dex: 'E', int: 'E', fai: 'D' }, damage: ['Phys'] },
  { name: 'Giant\'s Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { str: 4, fai: 14 }, scaling: { str: 'E', fai: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Godslayer\'s Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { str: 4, fai: 27 }, scaling: { str: 'E', fai: 'C' }, weight: 1.5, damage: ['Phys'] },
  { name: 'Golden Order Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true, req: { int: 17, fai: 17 }, scaling: { int: 'D', fai: 'D' }, damage: ['Phys'] },
  { name: 'Gravel Stone Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: false, hasMap: true },
  { name: 'Spiraltree Seal', weaponType: 61, classLabel: 'Sacred Seal', dlc: true, hasMap: true },
  { name: 'Chilling Perfume Bottle', weaponType: 89, classLabel: 'Perfume Bottle', dlc: true, hasMap: true },
  { name: 'Deadly Poison Perfume Bottle', weaponType: 89, classLabel: 'Perfume Bottle', dlc: true, hasMap: true },
  { name: 'Firespark Perfume Bottle', weaponType: 89, classLabel: 'Perfume Bottle', dlc: true, hasMap: true },
  { name: 'Frenzyflame Perfume Bottle', weaponType: 89, classLabel: 'Perfume Bottle', dlc: true, hasMap: true },
  { name: 'Lightning Perfume Bottle', weaponType: 89, classLabel: 'Perfume Bottle', dlc: true, hasMap: true },
  { name: 'Smithscript Dagger', weaponType: 91, classLabel: 'Throwing Blade', dlc: true, hasMap: true },
  { name: 'Backhand Blade', weaponType: 92, classLabel: 'Backhand Blade', dlc: true, hasMap: true },
  { name: 'Curseblade\'s Cirque', weaponType: 92, classLabel: 'Backhand Blade', dlc: false, hasMap: false },
  { name: 'Smithscript Cirque', weaponType: 92, classLabel: 'Backhand Blade', dlc: true, hasMap: true },
  { name: 'Leda\'s Sword', weaponType: 93, classLabel: 'Light Greatsword', dlc: true, hasMap: true },
  { name: 'Milady', weaponType: 93, classLabel: 'Light Greatsword', dlc: true, hasMap: true },
  { name: 'Rellana\'s Twin Blades', weaponType: 93, classLabel: 'Light Greatsword', dlc: false, hasMap: false },
  { name: 'Dragon-Hunter\'s Great Katana', weaponType: 94, classLabel: 'Great Katana', dlc: true, hasMap: true },
  { name: 'Great Katana', weaponType: 94, classLabel: 'Great Katana', dlc: true, hasMap: true },
  { name: 'Rakshasa\'s Great Katana', weaponType: 94, classLabel: 'Great Katana', dlc: true, hasMap: true },
  { name: 'Red Bear\'s Claw', weaponType: 95, classLabel: 'Beast Claw', dlc: true, hasMap: true },
]
